name: Build Documentation

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        #path: docs
        fetch-depth: 1

    - name: Get docfx
      run: |
        curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o docfx.zip
        unzip -d .docfx docfx.zip

    - name: Build docs
      run:  .docfx/docfx.exe
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: root
        server: 78.47.109.137
        #port: # default is 22
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        # will put all file under this path
        local_path: ./_site/* # default is ./*
        # files will copy to under remote_path
        remote_path: /var/www-thegraybook # default is /
        # sftp args
        # args: # optional
